[30기 김은지] modeling
wecode-bootcamp-korea/30-1st-WoowaSiblings-backend pull request #1
Opened 2022-03-02 03:43 UTC by thisiseunji

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 모델링 리뷰 전, 작성한 ERD기준으로 models.py 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- core, users, products, reviews, carts, orders, thirtyth 앱 생성 후, models.py 작성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- cart와 product_option table의 관계 설정 상 어려움
- 좋아요 모델링시, 범주 구분에 어려움이 있었음
<br />

## :: 기타 질문 및 특이 사항
- site image table의 앱 범주 구분을 어디에 해야할지 모르겠습니다. 따로 앱을 만들어야 할까요?

2022-03-02 12:41 UTC, kyeongraekim requested changes
전체적으로 클래스(케멀 케이스 & 단수), 테이블 네이밍 (스네이크 케이스 & 복수) 컨벤션 지켜주시면서 조금만 수정해주세요! 나머지 부분은 의도해드린대로 잘 작성해주신 것 같네요!~

2022-03-02 12:41 UTC, kyeongraekim commented on core/models.py
> +class Time_stamp(models.Model):
클래스 네이밍은 CamelCase 로 지어주시는 것 잊지 말아주세요!~

2022-03-02 12:41 UTC, kyeongraekim commented on orders/models.py
> +class Order_status_code:
전체적으로 클래스명 네이밍이 잘못 되어 있네요! 전반적으로 다 한 번 훑어주세요!~

2022-03-02 12:41 UTC, kyeongraekim commented on orders/models.py
> +        db_table = 'order_status_code'
테이블명은 복수로 해주셔야 합니다!~

2022-03-02 12:41 UTC, kyeongraekim commented on products/models.py
> +class Categories(models.Model):
클래스명은 단수 입니다!~

2022-03-03 01:56 UTC, kyeongraekim approved these changes
LGTM!~

2022-03-03 01:57 UTC, kyeongraekim commented
추후에 모델링 수정 소요가 언제든 생길 수 있는데 그 때 마다 필요한 브랜치 새로 파서 진행해주시면 됩니다!~

2022-03-03 01:57 UTC, merged

2022-03-03 02:19 UTC, thisiseunji commented
> 추후에 모델링 수정 소요가 언제든 생길 수 있는데 그 때 마다 필요한 브랜치 새로 파서 진행해주시면 됩니다!~

넵 감사합니다~~~!