[김동규] 장바구니 CRUD 기능 구현
wecode-bootcamp-korea/30-1st-WoowaSiblings-backend pull request #11
Opened 2022-03-08 09:35 UTC by pasitoapasito

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니(carts app)의 POST, GET, PATCH, DELETE 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 장바구니 생성(POST) 로직 구현
2. 장바구니 조회(GET) 로직 구현
3. 장바구니 수정(UPDATE) 로직 구현
4. 장바구니 삭제(DELETE) 로직 구현

- 위의 기능들 모두 signin_decorator를 활용하여 로그인 처리가 된 유저만 장바구니 기능을 이용할 수 있도록 함(토근 활용)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- get_or_create() 함수의 default 기능을 활용하여 실제로 동일 제품이 장바구니에 이미 존재할 경우 
   새롭게 장바구니에 해당 제품을 추가하는 것이 아닌, 수량만 증가시키는 로직을 구현할 수 있었습니다.

<br />

## :: 기타 질문 및 특이 사항
- results 리스트의 value 값들을 참조하는데 너무 긴 코드를 사용한 것 같아서 리팩토링을 이후에 시도해봐야 할 것 같습니다!!

2022-03-09 06:44 UTC, kyeongraekim requested changes

2022-03-09 06:44 UTC, kyeongraekim commented on orders/views.py
> +                cart[0].save()
get or create의 공식 문서 내용 처럼 cart, created 등으로 보다 명확한 변수선언을 부탁드려요! 인덱싱으로 진행을 하니 모호해보이는 경향이 느껴집니다~
파이썬 문법상 아래와 같은 변수선언이 가능하다는 점을 기억해주세요!~
a, b = c, d
a = c
b =d

2022-03-09 06:44 UTC, kyeongraekim commented on orders/views.py
> +                return JsonResponse({'message' : 'ADD_QUANTITY_TO_EXISTED_CART'}, status=204)
상태코드를 204 보다 올바른 상태코드를 고민해서 수정해주세요!

2022-03-09 06:44 UTC, kyeongraekim commented on orders/views.py
> +                                                discount_rate)/100) if cart.product_time.product.on_discount\
코드 가독성이 다소 어려워졌네요. 혹시 위에 변수로 선언할 부분은 따로 빼서 최대한 깔끔하게 정리해보실 수 있으실까요?

2022-03-09 06:44 UTC, kyeongraekim commented on orders/views.py
> +            if cart:
해당 부분도 .exists() 메소드를 써서 보다 효율적인 논리연산을 접목시켜보세요~

2022-03-09 06:47 UTC, pasitoapasito commented on orders/views.py
> +                cart[0].save()
넵 보다 효율적인 변수선언 방식으로 수정하겠습니다!!

2022-03-09 06:48 UTC, pasitoapasito commented on orders/views.py
> +                return JsonResponse({'message' : 'ADD_QUANTITY_TO_EXISTED_CART'}, status=204)
올바른 상태코드로 변경하겠습니다~!

2022-03-09 06:49 UTC, pasitoapasito commented on orders/views.py
> +            if cart:
넵 exists() 함수를 사용해서 수정해보겠습니다!!

2022-03-09 06:50 UTC, pasitoapasito commented on orders/views.py
> +                                                discount_rate)/100) if cart.product_time.product.on_discount\
넵!! 시도해보겠습니다!!

2022-03-10 07:37 UTC, kyeongraekim requested changes

2022-03-10 07:37 UTC, kyeongraekim commented on products/views.py
> +                'price'           : product.price if not product.stock == 0 else '',
다른 부분은 None으로 바꾸셨는데 이 부분의 else 리턴 값은 빈 문자열이네요! 의도하신 부분일까요?

2022-03-10 07:56 UTC, kyeongraekim approved these changes
LGTM!~

2022-03-10 07:58 UTC, merged