[김동규] 전체 페이지, 카테고리 페이지 기능 구현
wecode-bootcamp-korea/30-1st-WoowaSiblings-backend pull request #5
Opened 2022-03-05 09:05 UTC by pasitoapasito

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 전체 페이지와 카테고리 페이지의 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 전체 상품 정보를 json 객체 형태로 전달하는 views.py 로직 구현
2. 특정 카테고리에 포함된 상품 정보를 json 객체 형태로 전달하는 views.py 로직 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 장고 ORM의 Q객체 개념을 알게 되었습니다. 
- Q 객체를 통해 filter() 함수의 조건을 다양하게 설정할 수 있음을 배웠습니다. [카테고리 상품 정보 필터링]

<br />

2022-03-06 12:12 UTC, kyeongraekim requested changes
아래 내용 확인해보시고 수정해주세요!~

2022-03-06 12:12 UTC, kyeongraekim commented on products/urls.py
> +    path('/productlist', ProductListView.as_view()),
보다 restful 하게 URI를 설정해주세요! 앞 단에서 지정한 products로 해당 URI를 깔끔하게 마무리 지었다면 전체 상품에 대한 Get 요청이라는 내용을 유추할 수 있을 것 같네요!

2022-03-06 12:12 UTC, kyeongraekim commented on products/views.py
> +                )
- 가독성 및 연산 속소 향상을 위해서 리스트 컴프리헨션을 활용하여 Get 요청을 해보세요!

2022-03-06 12:12 UTC, kyeongraekim commented on products/views.py
> +            sorting  = request.GET.get('sort', '-created_at')
해당 sorting 기획이 최신순 이외에는 더 추가할 기능이 혹시 없었나요?

2022-03-06 12:12 UTC, kyeongraekim commented on products/views.py
> +                        'discount_price'  : float(product.price) * (1-discount_rate) if on_discount else '',
해당 부분은 빈문자열보다 Null 값으로 전달되어야 프론트가 추후에 다양한 방법으로 가공하기 더 편할 것 같네요!

2022-03-06 12:12 UTC, kyeongraekim commented on products/views.py
> +                discount_rate = float(product.productsdiscountrate_set.\
해당 형태로 보내주면 프론트에서 뒤 소수점 .00 등을 대신 제거해주는 기획이실까요?

2022-03-06 12:12 UTC, kyeongraekim commented on products/views.py
> +                likes         = product.like_set.all().aggregate(Count('product_id'))\
- aggregate 와 annotate 의 차이점을 비교해보시고 어느 것이 더 효율적인 방법일지 한 번 고민해보세요!
- 그리고 좋아요 숫자를 세는 것인데 위 두 가지 말고 그냥 역참조로 잡혀진 객체의 수를 카운트 메소드로 셀 수 있지 않을까요?

2022-03-06 12:14 UTC, pasitoapasito commented on products/urls.py
> +    path('/productlist', ProductListView.as_view()),
넵 고민해서 수정하겠습니다!!

2022-03-06 12:14 UTC, pasitoapasito commented on products/views.py
> +                )
넵 리스트 컨프리헨션으로 수정해보겠습니다!!

2022-03-06 12:17 UTC, pasitoapasito commented on products/views.py
> +            sorting  = request.GET.get('sort', '-created_at')
디폴트 값으로 최신순 sorting이 되는 것이고 프론트에서 URI 뒤에 쿼리스트링으로 ?sort="price" or "-price" 등을 넣어서 보내주면 sorting 되도록 기획한 코드였습니다!! 

좋아요 기준으로 sorting을 하고 싶어서 likes라는 변수는 만들어놨는데, products 테이블에서 like_cnt 같은 필드명이 없어서 좋아요를 정렬 기준으로 사용하지 못하고 있었습니다!!

2022-03-06 12:18 UTC, pasitoapasito commented on products/views.py
> +            sorting  = request.GET.get('sort', '-created_at')
제 생각에는 products 테이블에 likes_cnt 같은 필드명을 하나 추가해주면 가능할 듯 한데 월요일에 경래님께 직접 질문 드리고 답을 찾으려고 우선 likes 변수만 넣어놨습니다!!

2022-03-06 12:20 UTC, pasitoapasito commented on products/views.py
> +                        'discount_price'  : float(product.price) * (1-discount_rate) if on_discount else '',
원래 제가 Null 값을 넣었는데, 오늘 프론트 멤버분들이랑 통신 테스트를 하면서 빈 문자열이 더 좋을 것 같다고 해서 수정했었는데 다시 한 번 프론트분들이랑 의논하고 수정해보겠습니다!!

2022-03-06 12:21 UTC, pasitoapasito commented on products/views.py
> +                discount_rate = float(product.productsdiscountrate_set.\
넵!! float 형태로 보내면 프론트 로직에서 100을 곱해서 % 기호와 함께 화면에 보여주는 것을 통신 테스트로 확인했습니다!!

2022-03-06 12:21 UTC, pasitoapasito commented on products/views.py
> +                likes         = product.like_set.all().aggregate(Count('product_id'))\
aggregate() 함수와 annotate() 함수에 대해 더 고민해보고 수정해보겠습니다!!

2022-03-06 12:22 UTC, pasitoapasito commented on products/views.py
> +                likes         = product.like_set.all().aggregate(Count('product_id'))\
역참조로 잡혀진 객체 수를 카운트하는 방법을 고민해서 수정해보겠습니다!!

2022-03-07 07:32 UTC, kyeongraekim approved these changes
LGTM!~

2022-03-07 07:32 UTC, merged